name: Semgrep SAST

on:
  push:
    branches: [main]
  pull_request:

jobs:
  semgrep:
    name: Semgrep SAST
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: returntocorp/semgrep-action@v1
        with:
          config: 'p/ci'   # Recommended open-source rules
