name: Semgrep SAST

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: python3 -m pip install --upgrade pip semgrep

      - name: Run Semgrep SAST (HTML)
        run: semgrep ci --config=auto --html --output=semgrep-report.html
        continue-on-error: true

      - name: Upload Semgrep HTML report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-html-report
          path: semgrep-report.html
