name: Snyk Dependency Scan

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  snyk-sca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: snyk/actions/setup@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Snyk Open Source JSON report
        run: snyk test --json > snyk-sca.json

      - name: Install snyk-to-html
        run: npm install -g snyk-to-html

      - name: Convert JSON to HTML
        run: snyk-to-html -i snyk-sca.json -o snyk-sca-report.html

      - name: Upload Snyk HTML report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-sca-report
          path: snyk-sca-report.html
